<?php

return [
    'api_key' => env('RUNPOD_API_KEY'),
    'base_url' => env('RUNPOD_API_BASE_URL', 'https://rest.runpod.io/v1'),
    'default_image_name' => env('RUNPOD_DEFAULT_IMAGE_NAME', 'ghcr.io/open-webui/open-webui:ollama'),
    'default_template_id' => env('RUNPOD_DEFAULT_TEMPLATE_ID'),
    'default_container_disk_size_gb' => env('RUNPOD_DEFAULT_DISK_SIZE', 30),
    'default_volume_size_gb' => env('RUNPOD_DEFAULT_VOLUME_SIZE', 50),
    'default_volume_mount_path' => env('RUNPOD_VOLUME_MOUNT_PATH', '/root/.ollama'),
    'default_webui_port' => env('RUNPOD_WEBUI_PORT', 8080),
    'poll_interval_seconds' => env('RUNPOD_POLL_INTERVAL', 15),
    'poll_max_attempts' => env('RUNPOD_POLL_MAX_ATTEMPTS', 60),

    'gpu_tiers' => [
        'RTX_4090' => [
            'display' => 'NVIDIA RTX 4090',
            'vram_gb' => 24,
            'tps_estimate' => 85,
            'runpod_id' => 'NVIDIA GeForce RTX 4090',
            'hourly_rate' => 0.79,
            'performance_vs_gpt4' => 0.65,
            'performance_vs_claude35' => 0.60,
        ],
        'RTX_A6000' => [
            'display' => 'NVIDIA RTX A6000',
            'vram_gb' => 48,
            'tps_estimate' => 110,
            'runpod_id' => 'NVIDIA RTX A6000',
            'hourly_rate' => 1.49,
            'performance_vs_gpt4' => 0.80,
            'performance_vs_claude35' => 0.75,
        ],
        'A100_40GB' => [
            'display' => 'NVIDIA A100 40GB',
            'vram_gb' => 40,
            'tps_estimate' => 180,
            'runpod_id' => 'NVIDIA A100 40GB',
            'hourly_rate' => 2.99,
            'performance_vs_gpt4' => 1.10,
            'performance_vs_claude35' => 1.05,
        ],
        'A100_80GB' => [
            'display' => 'NVIDIA A100 80GB',
            'vram_gb' => 80,
            'tps_estimate' => 230,
            'runpod_id' => 'NVIDIA A100 80GB',
            'hourly_rate' => 4.49,
            'performance_vs_gpt4' => 1.25,
            'performance_vs_claude35' => 1.20,
        ],
        'H100' => [
            'display' => 'NVIDIA H100 80GB',
            'vram_gb' => 80,
            'tps_estimate' => 350,
            'runpod_id' => 'NVIDIA H100 80GB',
            'hourly_rate' => 7.99,
            'performance_vs_gpt4' => 1.80,
            'performance_vs_claude35' => 1.75,
        ],
    ],

    'recommended_models' => [
        'llama-3-8b-instruct' => [
            'display' => 'Llama 3 8B Instruct',
            'min_vram_gb' => 8,
            'recommended_gpu' => 'RTX_4090',
            'huggingface_id' => 'meta-llama/Meta-Llama-3-8B-Instruct',
            'ollama_tag' => 'llama3:8b',
            'category' => 'general',
        ],
        'llama-3-70b-instruct' => [
            'display' => 'Llama 3 70B Instruct',
            'min_vram_gb' => 40,
            'recommended_gpu' => 'A100_40GB',
            'huggingface_id' => 'meta-llama/Meta-Llama-3-70B-Instruct',
            'ollama_tag' => 'llama3:70b',
            'category' => 'general',
        ],
        'mistral-7b' => [
            'display' => 'Mistral 7B',
            'min_vram_gb' => 8,
            'recommended_gpu' => 'RTX_4090',
            'huggingface_id' => 'mistralai/Mistral-7B-Instruct-v0.3',
            'ollama_tag' => 'mistral:7b',
            'category' => 'general',
        ],
        'mixtral-8x7b' => [
            'display' => 'Mixtral 8x7B',
            'min_vram_gb' => 24,
            'recommended_gpu' => 'RTX_A6000',
            'huggingface_id' => 'mistralai/Mixtral-8x7B-Instruct-v0.1',
            'ollama_tag' => 'mixtral:8x7b',
            'category' => 'general',
        ],
        'codellama-34b' => [
            'display' => 'CodeLlama 34B',
            'min_vram_gb' => 24,
            'recommended_gpu' => 'RTX_A6000',
            'huggingface_id' => 'codellama/CodeLlama-34b-Instruct-hf',
            'ollama_tag' => 'codellama:34b',
            'category' => 'coding',
        ],
        'deepseek-coder-33b' => [
            'display' => 'DeepSeek Coder 33B',
            'min_vram_gb' => 24,
            'recommended_gpu' => 'RTX_A6000',
            'huggingface_id' => 'deepseek-ai/deepseek-coder-33b-instruct',
            'ollama_tag' => 'deepseek-coder:33b',
            'category' => 'coding',
        ],
        'phi-3-mini' => [
            'display' => 'Phi-3 Mini 3.8B',
            'min_vram_gb' => 4,
            'recommended_gpu' => 'RTX_4090',
            'huggingface_id' => 'microsoft/Phi-3-mini-4k-instruct',
            'ollama_tag' => 'phi3:mini',
            'category' => 'general',
        ],
        'gemma-2-9b' => [
            'display' => 'Gemma 2 9B',
            'min_vram_gb' => 8,
            'recommended_gpu' => 'RTX_4090',
            'huggingface_id' => 'google/gemma-2-9b-it',
            'ollama_tag' => 'gemma2:9b',
            'category' => 'general',
        ],
        'qwen2-72b' => [
            'display' => 'Qwen 2 72B',
            'min_vram_gb' => 40,
            'recommended_gpu' => 'A100_40GB',
            'huggingface_id' => 'Qwen/Qwen2-72B-Instruct',
            'ollama_tag' => 'qwen2:72b',
            'category' => 'general',
        ],
        'dolphin-mixtral-8x7b' => [
            'display' => 'Dolphin Mixtral 8x7B',
            'min_vram_gb' => 24,
            'recommended_gpu' => 'RTX_A6000',
            'huggingface_id' => 'cognitivecomputations/dolphin-mixtral-8x7b',
            'ollama_tag' => 'dolphin-mixtral:8x7b',
            'category' => 'creative',
        ],
    ],
];
